; Listing generated by Microsoft (R) Optimizing Compiler Version 19.41.34120.0 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?g_fSlew@@3_NA					; g_fSlew
PUBLIC	?g_modBase@@3PEADEA				; g_modBase
PUBLIC	?Slew@@3P6AXXZEA				; Slew
_BSS	SEGMENT
?g_fSlew@@3_NA DB 01H DUP (?)				; g_fSlew
	ALIGN	8

?g_modBase@@3PEADEA DQ 01H DUP (?)			; g_modBase
?Slew@@3P6AXXZEA DQ 01H DUP (?)				; Slew
_BSS	ENDS
PUBLIC	?DLLAttach@@YAKPEAUHINSTANCE__@@@Z		; DLLAttach
PUBLIC	?SlewEnableDisable@@YAXXZ			; SlewEnableDisable
PUBLIC	?RunMod@@YAXXZ					; RunMod
EXTRN	__imp_FreeLibraryAndExitThread:PROC
EXTRN	__imp_GetModuleHandleW:PROC
EXTRN	__imp_GetAsyncKeyState:PROC
EXTRN	MH_Initialize:PROC
EXTRN	MH_Uninitialize:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?DLLAttach@@YAKPEAUHINSTANCE__@@@Z DD imagerel $LN4
	DD	imagerel $LN4+51
	DD	imagerel $unwind$?DLLAttach@@YAKPEAUHINSTANCE__@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?RunMod@@YAXXZ DD imagerel $LN13
	DD	imagerel $LN13+73
	DD	imagerel $unwind$?RunMod@@YAXXZ
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?RunMod@@YAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?DLLAttach@@YAKPEAUHINSTANCE__@@@Z DD 020601H
	DD	030023206H
xdata	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\PC\source\repos\IE17-Client\IE17-Client\main.cpp
;	COMDAT ?RunMod@@YAXXZ
_TEXT	SEGMENT
?RunMod@@YAXXZ PROC					; RunMod, COMDAT

; 24   : {

$LN13:
	sub	rsp, 40					; 00000028H

; 25   :     Slew = (_FunctionOne)(g_modBase + 0x1F9D50);

	mov	rax, QWORD PTR ?g_modBase@@3PEADEA	; g_modBase
	add	rax, 2071888				; 001f9d50H
	mov	QWORD PTR ?Slew@@3P6AXXZEA, rax		; Slew
	npad	8
$LL2@RunMod:

; 26   : 
; 27   :     while (true)
; 28   :     {
; 29   : 
; 30   :         if (GetAsyncKeyState(VK_UP) & 1)

	mov	ecx, 38					; 00000026H
	call	QWORD PTR __imp_GetAsyncKeyState
	test	al, 1
	je	SHORT $LN4@RunMod

; 31   :         {
; 32   :             Slew();

	call	QWORD PTR ?Slew@@3P6AXXZEA		; Slew
$LN4@RunMod:

; 33   :         }
; 34   :         if (GetAsyncKeyState(VK_TAB) & 1)

	mov	ecx, 9
	call	QWORD PTR __imp_GetAsyncKeyState
	test	al, 1
	je	SHORT $LL2@RunMod

; 35   :         {
; 36   :             break; //uninject the dll
; 37   :         }
; 38   :     }
; 39   : }

	add	rsp, 40					; 00000028H
	ret	0
?RunMod@@YAXXZ ENDP					; RunMod
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\PC\source\repos\IE17-Client\IE17-Client\main.cpp
;	COMDAT ?SlewEnableDisable@@YAXXZ
_TEXT	SEGMENT
?SlewEnableDisable@@YAXXZ PROC				; SlewEnableDisable, COMDAT

; 13   :     if (g_fSlew)

	cmp	BYTE PTR ?g_fSlew@@3_NA, 0		; g_fSlew
	sete	BYTE PTR ?g_fSlew@@3_NA			; g_fSlew

; 14   :     {
; 15   :         g_fSlew = false;
; 16   :     }
; 17   :     else
; 18   :     {
; 19   :         g_fSlew = true;
; 20   :     }
; 21   : }

	ret	0
?SlewEnableDisable@@YAXXZ ENDP				; SlewEnableDisable
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\PC\source\repos\IE17-Client\IE17-Client\main.cpp
;	COMDAT ?DLLAttach@@YAKPEAUHINSTANCE__@@@Z
_TEXT	SEGMENT
hModule$ = 48
?DLLAttach@@YAKPEAUHINSTANCE__@@@Z PROC			; DLLAttach, COMDAT

; 42   : {

$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx

; 43   :     MH_Initialize();

	call	MH_Initialize

; 44   :     g_modBase = (char*)GetModuleHandle(NULL);

	xor	ecx, ecx
	call	QWORD PTR __imp_GetModuleHandleW
	mov	QWORD PTR ?g_modBase@@3PEADEA, rax	; g_modBase

; 45   :     RunMod();

	call	?RunMod@@YAXXZ				; RunMod

; 46   :     MH_Uninitialize();

	call	MH_Uninitialize

; 47   :     FreeLibraryAndExitThread(hModule, 0);

	xor	edx, edx
	mov	rcx, rbx
	call	QWORD PTR __imp_FreeLibraryAndExitThread
	int	3
$LN3@DLLAttach:
?DLLAttach@@YAKPEAUHINSTANCE__@@@Z ENDP			; DLLAttach
_TEXT	ENDS
END
